# It is adviced when storing chat history we need to distinguish which response was generated by AI and what
# was provided by Human as an input.
from langchain_core.messages import HumanMessage,AIMessage,SystemMessage
from langchain_openai import ChatOpenAI

model = ChatOpenAI()

messages = [
    SystemMessage(content="You are a helpful AI assistant"),
    HumanMessage(content="In 2 lines tell me about Langchain")
]

result = model.invoke(messages)
messages.append(AIMessage(result.content))

print(messages)